[server]
host: 0.0.0.0
enable_debug_logging: False
config_path: ~/printer_config

[authorization]
enabled: true
trusted_clients:
   127.0.0.1   
   192.168.1.0/24
cors_domains:
# Allow CORS requests for mainsail


[update_manager]
enable_repo_debug: False
#   When set to True moonraker will bypass repo validation and allow
#   updates from unofficial remotes and/or branches.  Updates on
#   detached repos are also allowed.  This option is intended for
#   developers and should not be used on production machines.  The
#   default is False.
enable_auto_refresh: True
#   When set to True Moonraker will attempt to fetch status about
#   available updates roughly every 24 hours, between 12am-4am.
#   When set to False Moonraker will only fetch update state on startup
#   and clients will need to request that Moonraker updates state.  The
#   default is False.
distro: debian
#   The disto in which moonraker has been installed.  Currently the
#   update manager only supports "debian", which encompasses all of
#   its derivatives.  The default is debain.

[update_manager client KlipperScreen]
type: git_repo
path: /home/pi/KlipperScreen
origin: https://github.com/jordanruthe/KlipperScreen.git
env: /home/pi/.KlipperScreen-env/bin/python
requirements: scripts/KlipperScreen-requirements.txt
install_script: scripts/KlipperScreen-install.sh

[update_manager client fluidd]
type: web
repo: cadriel/fluidd
#   This is the GitHub repo of the client, in the format of user/client.
#   For example, this could be set to cadriel/fluidd to update Fluidd or
#   meteyou/mainsail to update Mainsail.  This parameter must be provided.
path: /home/pi/fluidd
#   The path to the client's files on disk.  This parameter must be provided.

[update_manager client mainsail]
type: web
repo: meteyou/mainsail
#   This is the GitHub repo of the client, in the format of user/client.
#   For example, this could be set to cadriel/fluidd to update Fluidd or
#   meteyou/mainsail to update Mainsail.  This parameter must be provided.
path: /home/pi/mainsail
#   The path to the client's files on disk.  This parameter must be provided.

[power tplink_wifi_switch]
type: tplink_smartplug
address: 192.168.3.35
